2021-03-28 12:29:10.3679 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 12:29:19.8459 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 12:29:20.8282 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 12:29:22.2767 INFO :	MainWindowModel.AutoConnect 
	AutoConnect
2021-03-28 12:29:31.3074 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 12:29:47.1956 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 12:42:38.3136 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 12:45:02.2339 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 12:49:13.2143 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 12:50:34.5587 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 12:58:09.3854 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 12:59:07.2279 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:01:47.7586 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:02:48.3248 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:06:24.3954 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:07:11.5715 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:12:55.8616 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:15:12.3795 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:16:17.7430 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:17:56.8215 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:19:48.6868 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:22:57.5380 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:24:17.7065 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:27:59.1055 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:30:54.9988 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:34:37.5865 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:34:40.8937 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> http://127.0.0.1:8082/thong-tin/NXGNPSV0378291E5997600/
2021-03-28 13:34:41.0046 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_info_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 806
2021-03-28 13:35:02.3603 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:35:02.9301 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> http://127.0.0.1:8082/sao-luu/danh-sach/NXGNPSV0378291E5997600/
2021-03-28 13:35:02.9301 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_list_data_backup(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 410
2021-03-28 13:35:24.3872 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:35:24.7702 ERROR :	<get_setting_to_server>d__39.MoveNext 
	[get_setting_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_setting_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 738
2021-03-28 13:35:40.3602 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:35:42.3417 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> http://127.0.0.1:8082/thong-tin/NXGNPSV0378291E5997600/
2021-03-28 13:35:42.5416 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_info_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 806
2021-03-28 13:36:03.8482 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:36:04.1891 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> http://127.0.0.1:8082/sao-luu/danh-sach/NXGNPSV0378291E5997600/
2021-03-28 13:36:04.2260 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_list_data_backup(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 410
2021-03-28 13:36:25.4556 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:36:25.6424 ERROR :	<get_setting_to_server>d__39.MoveNext 
	[get_setting_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_setting_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 738
2021-03-28 13:36:46.9056 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:36:47.2205 ERROR :	MainUtility.get_list_data_connect 
	[check_is_logged] -> http://127.0.0.1:8082/ket-noi/danh-sach/NXGNPSV0378291E5997600/
2021-03-28 13:36:47.2214 ERROR :	MainUtility.get_list_data_connect 
	[check_is_logged] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_list_data_connect(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 470
2021-03-28 13:37:08.3946 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:37:08.6933 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 13:37:20.9241 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:38:03.6058 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:38:48.7410 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:41:43.8437 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:43:21.2659 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:44:14.1665 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:47:48.0479 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:47:50.4964 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> http://127.0.0.1:8082/thong-tin/NXGNPSV0378291E5997600/
2021-03-28 13:47:50.6390 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_info_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 806
2021-03-28 13:48:11.8425 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:48:12.2485 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> http://127.0.0.1:8082/sao-luu/danh-sach/NXGNPSV0378291E5997600/
2021-03-28 13:48:12.2554 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_list_data_backup(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 410
2021-03-28 13:48:35.6601 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:48:37.4497 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> http://127.0.0.1:8082/thong-tin/NXGNPSV0378291E5997600/
2021-03-28 13:48:37.5693 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_info_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 806
2021-03-28 13:49:31.5143 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:49:33.6586 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> http://127.0.0.1:8082/thong-tin/NXGNPSV0378291E5997600/
2021-03-28 13:49:33.7804 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_info_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 806
2021-03-28 13:49:55.1550 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:49:55.4324 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> http://127.0.0.1:8082/sao-luu/danh-sach/NXGNPSV0378291E5997600/
2021-03-28 13:49:55.4324 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_list_data_backup(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 410
2021-03-28 13:50:56.0066 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:50:58.5504 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> http://127.0.0.1:8082/thong-tin/NXGNPSV0378291E5997600/
2021-03-28 13:50:58.7169 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_info_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 806
2021-03-28 13:51:19.9459 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:51:20.2551 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> http://127.0.0.1:8082/sao-luu/danh-sach/NXGNPSV0378291E5997600/
2021-03-28 13:51:20.2551 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_list_data_backup(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 410
2021-03-28 13:51:41.5309 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:51:41.8186 ERROR :	<get_setting_to_server>d__39.MoveNext 
	[get_setting_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_setting_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 738
2021-03-28 13:52:03.0981 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:52:03.5573 ERROR :	MainUtility.get_list_data_connect 
	[check_is_logged] -> http://127.0.0.1:8082/ket-noi/danh-sach/NXGNPSV0378291E5997600/
2021-03-28 13:52:03.5573 ERROR :	MainUtility.get_list_data_connect 
	[check_is_logged] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_list_data_connect(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 470
2021-03-28 13:52:24.8613 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 13:52:25.2273 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 13:52:33.3850 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:52:47.3182 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:55:34.3191 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:55:36.6105 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> http://127.0.0.1:8082/thong-tin/NXGNPSV0378291E5997600/
2021-03-28 13:55:36.7791 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_info_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 806
2021-03-28 13:56:09.3033 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 13:56:12.2351 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> http://127.0.0.1:8082/thong-tin/NXGNPSV0378291E5997600/
2021-03-28 13:56:12.6602 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_info_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 806
2021-03-28 17:57:00.3297 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 17:57:04.5800 ERROR :	LogginView.check_is_logged 
	[check_is_logged] -> System.Net.WebException: No connection could be made because the target machine actively refused it. No connection could be made because the target machine actively refused it.
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Views.LogginView.check_is_logged() in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Views\LogginView.xaml.cs:line 44
2021-03-28 17:58:38.0063 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 17:58:41.5905 ERROR :	LogginView.check_is_logged 
	[check_is_logged] -> System.Net.WebException: No connection could be made because the target machine actively refused it. No connection could be made because the target machine actively refused it.
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Views.LogginView.check_is_logged() in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Views\LogginView.xaml.cs:line 44
2021-03-28 18:02:37.0259 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:02:39.9892 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> http://127.0.0.1:8082/thong-tin/NXGNPSV0378291E5997600/
2021-03-28 18:02:40.2076 ERROR :	MainUtility.get_info_to_server 
	[get_info_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_info_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 806
2021-03-28 18:03:01.6192 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 18:03:02.0000 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> http://127.0.0.1:8082/sao-luu/danh-sach/NXGNPSV0378291E5997600/
2021-03-28 18:03:02.0121 ERROR :	<get_list_data_backup>d__30.MoveNext 
	[check_is_logged] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_list_data_backup(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 410
2021-03-28 18:03:23.3102 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 18:03:24.3809 ERROR :	<get_setting_to_server>d__39.MoveNext 
	[get_setting_to_server] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_setting_to_server(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 738
2021-03-28 18:03:45.6254 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 18:03:45.9078 ERROR :	MainUtility.get_list_data_connect 
	[check_is_logged] -> http://127.0.0.1:8082/ket-noi/danh-sach/NXGNPSV0378291E5997600/
2021-03-28 18:03:45.9078 ERROR :	MainUtility.get_list_data_connect 
	[check_is_logged] -> System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.get_list_data_connect(AppJson configs) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 470
2021-03-28 18:04:07.1336 ERROR :	MainUtility.save_log_agent 
	[save_log_agent] -> System.Net.WebException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TransferWorker.UI.Utility.MainUtility.save_log_agent(String logcontent, String function, Int32 status, Int32 type, String email_loggin) in D:\TSG_BACKUP\ByteSave\ByteSavefase2\TransferWorker.UI\Utility\MainUtility.cs:line 851
2021-03-28 18:04:08.0309 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 18:04:24.4408 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:08:42.1477 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:08:49.8770 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 18:08:51.0117 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:08:52.0836 INFO :	MainWindowModel.AutoConnect 
	AutoConnect
2021-03-28 18:08:58.3526 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:09:06.8542 INFO :	<GetListFileFromCloud>d__30.MoveNext 
	GetListFileFromCloud
2021-03-28 18:09:07.1733 INFO :	<GetListFileFromCloud>d__30.MoveNext 
	[{"FileName":".LastVersion/Avalonia.Android/ActivityTracker.cs","Hash":36181605,"Length":1267,"LastModified":"2021-03-18T10:54:32","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T08:51:06"},{"FileName":".LastVersion/Avalonia.Android/cscsc.txt","Hash":28068188,"Length":0,"LastModified":"2021-03-18T08:48:12","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T08:48:12"},{"FileName":".LastVersion/Readme.txt","Hash":33163964,"Length":926,"LastModified":"2021-03-18T21:53:02","LastModifiedDisplay":null,"CreatedTime":"2021-03-05T00:09:38"},{"FileName":"/ActivityTracker.cs","Hash":14421545,"Length":1237,"LastModified":"2021-03-17T16:27:47","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:27:47"},{"FileName":"/AndroidPlatform.cs","Hash":35567111,"Length":2960,"LastModified":"2021-03-17T16:27:48","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:27:48"},{"FileName":"/AndroidThreadingInterface.cs","Hash":65066874,"Length":2471,"LastModified":"2021-03-17T16:27:49","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:27:49"},{"FileName":"/AppBuilder.cs","Hash":34160229,"Length":369,"LastModified":"2021-03-17T16:27:51","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:27:51"},{"FileName":"/Avalonia.Android.csproj","Hash":63238509,"Length":591,"LastModified":"2021-03-17T16:27:52","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:27:52"},{"FileName":"/Avalonia.Android/ActivityTracker.cs","Hash":11679222,"Length":1237,"LastModified":"2021-03-17T16:54:40","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:54:40"},{"FileName":"/app.config","Hash":35410979,"Length":460,"LastModified":"2021-03-17T16:27:50","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:27:50"},{"FileName":"02. TONG MAT BANG/0.DMBV.dwg","Hash":57416410,"Length":351392,"LastModified":"2021-03-25T12:21:00","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T12:21:00"},{"FileName":"02. TONG MAT BANG/1.SDNL.dwg","Hash":61940669,"Length":271702,"LastModified":"2021-03-25T12:21:01","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T12:21:01"},{"FileName":"02. TONG MAT BANG/2.MAT BANG CAP DIEN.dwg","Hash":15193904,"Length":1874050,"LastModified":"2021-03-25T12:21:01","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T12:21:01"},{"FileName":"02. TONG MAT BANG/3.CHONG SET.dwg","Hash":6303833,"Length":751850,"LastModified":"2021-03-25T11:15:13","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T11:15:13"},{"FileName":"02. TONG MAT BANG/5.CHI TIET LAP DAT.dwg","Hash":40452378,"Length":1001053,"LastModified":"2021-03-25T11:15:15","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T11:15:15"},{"FileName":"02. TONG MAT BANG/TRẠM BƠM TNT/1.SDNL TỦ BƠM TNT.DWG","Hash":36009496,"Length":956872,"LastModified":"2021-03-25T10:32:37","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:32:37"},{"FileName":"02. TONG MAT BANG/TRẠM BƠM TNT/1.SDNL TỦ BƠM TNT.bak","Hash":19634871,"Length":960497,"LastModified":"2021-03-25T10:32:34","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:32:34"},{"FileName":"02. TONG MAT BANG/TRẠM BƠM TNT/2.CHI TIET HỐ GA BƠM NƯỚC THẢI PTLC.bak","Hash":22584602,"Length":442880,"LastModified":"2021-03-25T10:32:39","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:32:39"},{"FileName":"02. TONG MAT BANG/TRẠM BƠM TNT/2.CHI TIET HỐ GA BƠM NƯỚC THẢI PTLC.dwg","Hash":32903719,"Length":478823,"LastModified":"2021-03-25T10:32:40","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:32:40"},{"FileName":"02. TONG MAT BANG/TRẠM BƠM TNT/3.MAT BANG CAP DIEN TRAM BOM TNT.bak","Hash":1669504,"Length":502560,"LastModified":"2021-03-25T10:32:43","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:32:43"},{"FileName":"02. TONG MAT BANG/TRẠM BƠM TNT/3.MAT BANG CAP DIEN TRAM BOM TNT.dwg","Hash":14696841,"Length":504928,"LastModified":"2021-03-25T10:32:44","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:32:44"},{"FileName":"02. TONG MAT BANG/TRẠM BƠM TNT/XR KHUNG A1 PVT PTLC TMDM.dwg","Hash":49056616,"Length":79520,"LastModified":"2021-03-25T10:32:46","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:32:46"},{"FileName":"02. TONG MAT BANG/TRẠM BƠM TNT/XREF_PTLC TMDM_CQSV.dwg","Hash":54963967,"Length":25399744,"LastModified":"2021-03-25T10:33:07","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:33:07"},{"FileName":"02. TONG MAT BANG/TRẠM BƠM TNT/Xref.MB.TuongxayTumMai.dwg","Hash":8879859,"Length":449312,"LastModified":"2021-03-25T10:32:48","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:32:48"},{"FileName":"02. TONG MAT BANG/XR KHUNG A1 PVT PTLC TMDM.dwg","Hash":32459944,"Length":79520,"LastModified":"2021-03-25T10:31:17","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:31:17"},{"FileName":"02. TONG MAT BANG/XREF_PTLC TMDM_CQSV.dwg","Hash":47033410,"Length":25716055,"LastModified":"2021-03-25T10:32:33","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:32:33"},{"FileName":"02. TONG MAT BANG/Xref.MB.TuongxayTumMai.dwg","Hash":22935716,"Length":449312,"LastModified":"2021-03-25T10:31:21","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:31:21"},{"FileName":"1.TBA - F4-T3B/TBA 2000kVA TMDM(HC ĐIỆN LỰC).dwg","Hash":50108275,"Length":1795372,"LastModified":"2021-03-25T10:11:26","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:11:26"},{"FileName":"1.TBA - F4-T3B/XR KHUNG A1 PVT PTLC TMDM.dwg","Hash":39386387,"Length":80000,"LastModified":"2021-03-25T10:11:27","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:11:27"},{"FileName":"1.TBA - F4-T3B/XREF_PTLC TMDM_CQSV.dwg","Hash":50884775,"Length":3802080,"LastModified":"2021-03-25T10:11:29","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T10:11:29"},{"FileName":"Avalonia.Android/ActivityTracker.cs","Hash":10326036,"Length":1123,"LastModified":"2021-03-18T10:54:33","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:56:28"},{"FileName":"Avalonia.Android/AndroidPlatform.cs","Hash":36213758,"Length":2960,"LastModified":"2021-03-17T16:59:13","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:59:13"},{"FileName":"Avalonia.Android/AndroidThreadingInterface.cs","Hash":29643721,"Length":2471,"LastModified":"2021-03-17T16:59:17","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:59:17"},{"FileName":"Avalonia.Android/AppBuilder.cs","Hash":43256217,"Length":369,"LastModified":"2021-03-17T16:59:18","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:59:18"},{"FileName":"Avalonia.Android/Avalonia.Android.csproj","Hash":39179857,"Length":591,"LastModified":"2021-03-17T16:59:18","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:59:18"},{"FileName":"Avalonia.Android/New Text Document.txt","Hash":40764822,"Length":0,"LastModified":"2021-03-18T09:56:07","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T09:56:07"},{"FileName":"Avalonia.Android/New folder/123456.txt","Hash":51319244,"Length":0,"LastModified":"2021-03-18T08:24:24","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T08:24:24"},{"FileName":"Avalonia.Android/New folder/New Text Document.txt","Hash":31614998,"Length":0,"LastModified":"2021-03-18T08:24:19","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T08:24:19"},{"FileName":"Avalonia.Android/app.config","Hash":5631066,"Length":460,"LastModified":"2021-03-17T16:59:18","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T16:59:18"},{"FileName":"Avalonia.Android/cscsc.txt","Hash":7486778,"Length":27,"LastModified":"2021-03-18T08:48:12","LastModifiedDisplay":null,"CreatedTime":"2021-03-17T23:14:10"},{"FileName":"Crack/JetbrainsIdesCrack-3.4-release-enc.jar","Hash":31307802,"Length":1063221,"LastModified":"2021-03-28T12:00:28","LastModifiedDisplay":null,"CreatedTime":"2021-03-28T12:00:28"},{"FileName":"Crack/Readme.txt","Hash":57687328,"Length":1565,"LastModified":"2021-03-28T12:00:29","LastModifiedDisplay":null,"CreatedTime":"2021-03-28T12:00:29"},{"FileName":"Crack/VirtualBox-6.1.18-142142-Win.exe","Hash":8106798,"Length":108257728,"LastModified":"2021-03-28T12:02:27","LastModifiedDisplay":null,"CreatedTime":"2021-03-28T12:02:27"},{"FileName":"Crack/aa - Copy.txt","Hash":61688809,"Length":0,"LastModified":"2021-03-28T12:00:26","LastModifiedDisplay":null,"CreatedTime":"2021-03-28T12:00:26"},{"FileName":"Crack/aa.txt","Hash":2852789,"Length":0,"LastModified":"2021-03-28T12:00:27","LastModifiedDisplay":null,"CreatedTime":"2021-03-28T12:00:27"},{"FileName":"Crack/log.txt","Hash":5568949,"Length":320,"LastModified":"2021-03-28T12:00:28","LastModifiedDisplay":null,"CreatedTime":"2021-03-28T12:00:28"},{"FileName":"Crack/log2.txt.txt","Hash":4443087,"Length":320,"LastModified":"2021-03-28T12:00:28","LastModifiedDisplay":null,"CreatedTime":"2021-03-28T12:00:28"},{"FileName":"Crack/xampp-windows-x64-8.0.3-0-VS16-installer.exe","Hash":16384677,"Length":164581664,"LastModified":"2021-03-28T12:07:27","LastModifiedDisplay":null,"CreatedTime":"2021-03-28T12:07:27"},{"FileName":"New folder/New Text Document (2).txt","Hash":64651675,"Length":0,"LastModified":"2021-03-08T10:07:46","LastModifiedDisplay":null,"CreatedTime":"2021-03-08T10:07:46"},{"FileName":"New folder/New Text Document.txt","Hash":13815511,"Length":72,"LastModified":"2021-03-08T10:07:47","LastModifiedDisplay":null,"CreatedTime":"2021-03-08T10:07:47"},{"FileName":"Xref.MB.TuongxayTumMai.dwg","Hash":5871419,"Length":449312,"LastModified":"2021-03-25T16:23:02","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T16:23:02"},{"FileName":"ab.py","Hash":19264108,"Length":140,"LastModified":"2021-03-25T16:56:01","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T16:56:01"},{"FileName":"apktool.bat","Hash":4417230,"Length":1101,"LastModified":"2021-03-25T16:58:00","LastModifiedDisplay":null,"CreatedTime":"2021-03-25T16:58:00"},{"FileName":"log2.txt.txt","Hash":15117700,"Length":320,"LastModified":"2021-03-28T12:00:27","LastModifiedDisplay":null,"CreatedTime":"2021-03-28T12:00:27"},{"FileName":"src/Android/Avalonia.Android/ActivityTracker.cs","Hash":2569844,"Length":1123,"LastModified":"2021-03-18T21:59:27","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:27"},{"FileName":"src/Android/Avalonia.Android/AndroidPlatform.cs","Hash":58813504,"Length":2960,"LastModified":"2021-03-18T21:59:28","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:28"},{"FileName":"src/Android/Avalonia.Android/AndroidThreadingInterface.cs","Hash":63289421,"Length":2471,"LastModified":"2021-03-18T21:59:29","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:29"},{"FileName":"src/Android/Avalonia.Android/AppBuilder.cs","Hash":14173886,"Length":369,"LastModified":"2021-03-18T21:59:30","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:30"},{"FileName":"src/Android/Avalonia.Android/Avalonia.Android.csproj","Hash":23431800,"Length":591,"LastModified":"2021-03-18T21:59:31","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:31"},{"FileName":"src/Android/Avalonia.Android/New Text Document.txt","Hash":7307551,"Length":0,"LastModified":"2021-03-18T21:59:31","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:31"},{"FileName":"src/Android/Avalonia.Android/New folder/123456.txt","Hash":22525719,"Length":0,"LastModified":"2021-03-18T21:59:32","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:32"},{"FileName":"src/Android/Avalonia.Android/app.config","Hash":30018436,"Length":460,"LastModified":"2021-03-18T21:59:30","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:30"},{"FileName":"src/Android/Avalonia.Android/cscsc.txt","Hash":61617225,"Length":27,"LastModified":"2021-03-18T21:59:31","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:31"},{"FileName":"src/JetbrainsIdesCrack-3.4-release-enc.jar","Hash":66454027,"Length":1063221,"LastModified":"2021-03-18T21:59:26","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:26"},{"FileName":"src/New Text Document (2).txt","Hash":35021870,"Length":0,"LastModified":"2021-03-18T21:59:26","LastModifiedDisplay":null,"CreatedTime":"2021-03-18T21:59:26"}]
2021-03-28 18:09:52.5760 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:10:21.5642 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:13:07.5737 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:13:15.8400 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 18:13:16.8092 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:13:17.2609 INFO :	MainWindowModel.AutoConnect 
	AutoConnect
2021-03-28 18:14:27.3450 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:15:25.3112 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:15:27.7869 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:15:30.0162 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:18:05.1957 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:18:33.6007 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 18:18:34.4679 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:18:35.0420 INFO :	MainWindowModel.AutoConnect 
	AutoConnect
2021-03-28 18:19:01.3104 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:21:35.1812 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:26:53.9508 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:30:28.6870 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:30:59.0185 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 18:30:59.8271 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:31:00.3037 INFO :	MainWindowModel.AutoConnect 
	AutoConnect
2021-03-28 18:31:04.3829 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:33:11.6145 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:36:12.1726 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:36:20.8250 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 18:36:21.8205 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:36:22.2324 INFO :	MainWindowModel.AutoConnect 
	AutoConnect
2021-03-28 18:37:00.0088 INFO :	LogginView.InstallMT 
	InstallMT 
2021-03-28 18:37:19.8125 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 18:37:20.8447 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:37:21.4288 INFO :	MainWindowModel.AutoConnect 
	AutoConnect
2021-03-28 18:41:52.4228 INFO :	<InstallMT>d__29.MoveNext 
	InstallMT 
2021-03-28 18:42:05.4474 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 18:42:06.4679 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:42:06.9746 INFO :	MainWindowModel.AutoConnect 
	AutoConnect
2021-03-28 18:42:20.9883 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:43:02.6636 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:43:45.2902 INFO :	<InstallMT>d__29.MoveNext 
	InstallMT 
2021-03-28 18:44:33.3952 INFO :	<InstallMT>d__29.MoveNext 
	InstallMT 
2021-03-28 18:45:46.4169 INFO :	<InstallMT>d__29.MoveNext 
	InstallMT 
2021-03-28 18:46:33.6291 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 18:46:34.4719 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:46:34.9121 INFO :	MainWindowModel.AutoConnect 
	AutoConnect
2021-03-28 18:46:54.5866 INFO :	<InstallMT>d__29.MoveNext 
	InstallMT 
2021-03-28 18:47:13.9407 INFO :	MainWindowModel..ctor 
	MainWindowModel
2021-03-28 18:47:14.7792 INFO :	ConfigMenuViewModel..ctor 
	ConfigMenuViewModel  System.Collections.Generic.List`1[TransferWorker.UI.Models.connect_bytesave]
2021-03-28 18:47:15.2163 INFO :	MainWindowModel.AutoConnect 
	AutoConnect
2021-03-28 23:44:19.5213 INFO :	<InstallMT>d__29.MoveNext 
	InstallMT 
2021-03-28 23:45:19.0993 INFO :	<InstallMT>d__29.MoveNext 
	InstallMT 
2021-03-28 23:46:23.5045 INFO :	<InstallMT>d__29.MoveNext 
	InstallMT 
2021-03-28 23:49:59.1354 INFO :	<InstallMT>d__29.MoveNext 
	InstallMT 
